### ISSUE TITLE
Autocomplete is not correcctly updating with options func

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#438] opened 2022-10-28 08:09 UTC
### Reproduction

https://formkit.link/970cb2d1618517082137421d9d152704

### Describe the bug

When using an autocomplete and setting an initial `value: 1` while there are no options, the `1` gets shown. As soon as the options get set, the `1` does not change to the label of value 1. I think this is a bug.

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment] 2022-10-29 03:04
This is actually working as intended — if no matching option is provided, FormKit is left in a tricky position — it doesn't know that you are loading options outside of its "sanctioned" ways of loading functions so it decides showing *something* to the user is better than showing nothing at all.

However, the ideal way to handle this edge case is to use an `option-loader` prop. This allows you to load the label/value pair for a single option, even async. Ideally this would be used to do a lookup of your value (`1`) in your case and display the appropriate item. This also means a more expensive lookup of all available options doesn't need to occur until a user interacts with the input. In this case, FormKit can know you are trying to load the option and will display a loading state. For example:

https://formkit.link/9265f6bcce491e42d5cc2d2909e21ec9

Hopefully that makes sense. FWIW — this is actually a killer feature of the Autocomplete vs some of the existing options on the market since it lets you have really nuanced control over the re-hydrating of your options but still has a small API surface area to learn.

Ok, since this is working as intended I'm going to close this issue — good luck 👍

**Closed by justin-schroeder** 2022-10-29 03:04 UTC
Labels: 🐛 bug-report, Pro
