### ISSUE TITLE
Taglist component : Select multiple entries without closing dropdown between each click

### ISSUE THREAD

**Issue by aousadou** [formkit/formkit#540] opened 2023-01-14 13:36 UTC
### Reproduction

https://formkit.com/inputs/taglist#basic-example

### Describe the bug

There is no way to configure taglist component to avoid closing of dropdown between each click. I want to select multiple entries without reopening dropdown at each selection.

Discussed here : https://discord.com/channels/793529058377072650/940340536747896842/1063481768688222238

### Environment

N/A

**Comment by sashamilenkovic** [comment] 2023-01-17 15:23
@aousadou If you give the playground a hard reload, this should work now: https://formkit.link/3445f04d4b5b551355783c4dce265db2. Notice the prop `closeOnSelect`, setting it to `false` will give you the behavior you're looking for.

**Comment by sashamilenkovic** [comment] 2023-01-17 15:31
@aousadou I'm going to close this for now, but reply to me here or on discord if you have any issues.

**Closed by sashamilenkovic** 2023-01-17 15:31 UTC
Labels: 🪄 enhancement

**Comment by aousadou** [comment] 2023-01-17 16:46
@sashamilenkovic thanks ! I will test it and give you a feedback if i have any issues.

**Comment by Lockev** [comment] 2023-01-18 10:53
Hello @sashamilenkovic, I'm from aousadou's dev team. 

I'm currently trying to update our form builder with this new closeOnSelect prop. However, I am unable to reproduce the desired behaviour on both our app and the provided playground. Do you have any idea on what could have happened ?

Our formkit config currently is : 
"@formkit/pro": "^1.0.0-alpha.53",
"@formkit/vue": "^1.0.0-beta.12"

**Comment by sashamilenkovic** [comment] 2023-01-18 13:08
@Lockev Hey! So in the playground example I provided, you're saying the listbox is closing when you make a selection still? Did you give the playground a hard reload?

**Comment by Lockev** [comment] 2023-01-18 14:30
Yes I actually just double-checked in this playground (https://formkit.link/3445f04d4b5b551355783c4dce265db2) provided above, and it still closes after each selection (even after a hard reload) ; same behavior on our app. 

Let me know if you'd like a video for reproduction purposes

**Comment by sashamilenkovic** [comment] 2023-01-18 14:38
@Lockev Well, it's working for me on multiple browsers, so I'm having a hard time replicating. If you visit the docs for it: [](https://formkit.com/inputs/taglist#close-on-select), is this also not working for you?

**Comment by Lockev** [comment] 2023-01-18 15:53
@sashamilenkovic Then I most likely found a bug that I wouldn't have believed possible (cf video bellow)

As for information, I use Arc as my primary browser (Chromium engine)

I've tried the feature on 3 different browsers, video order : Arc, Chrome, Brave. Which are suppose to run the same engine. But for some reason I cannot explain, the closeOnSelect feature is lock on true while using Arc. 

In the video it does showcase one other bug (or maybe feature I'm not quite sure about the intended behavior). At 0:47, using Chrome you can see the search reset itself after selecting one option.

.

Thank you Formkit team for addressing our ticket this quickly, your project is 🔥

https://user-images.githubusercontent.com/54106288/213217166-2f12323c-288d-4452-967c-8083e3072fd4.mov

**Comment by justin-schroeder** [comment] 2023-01-18 16:16
🤔 I have the arc browser too. I just checked and it worked just fine. I'd be willing to bet you have a cached version of the remote dependencies. Try opening the dev tools in arc, go to the network tab, and disable cache.

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/1950463/213231033-2467e529-71d7-4517-a098-ff817e38839c.png">

Then hold shift and click the ol’ refresh button.

**Comment by Lockev** [comment] 2023-01-18 17:03
You guessed right, thanks a lot 😃
