### ISSUE TITLE
FormKit disabled in Nuxt 3.0.0-rc.11

### ISSUE THREAD

**Issue by nosizejosh** [formkit/formkit#393] opened 2022-09-24 00:08 UTC
### Reproduction

none 

### Describe the bug

WARN Module FormKit is disabled due to incompatibility issues: 17:03:33

[nuxt] Nuxt version ^3.0.0 is required but currently using 3.0.0-rc.11
and I tried npm i @formkit/nuxt@next as suggested from https://github.com/formkit/formkit/issues/383 but still disabled

### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by Zielgestalt** [comment] 2022-09-24 11:19
Same here.

**Comment by Zielgestalt** [comment] 2022-09-24 11:24
No, sorry, for me @formkit/nuxt@next works now with Nuxt3 RC11

**Comment by justin-schroeder** [comment] 2022-09-24 11:24
A nuxt update to version constraints caused this, but it is fixed on the `@next` tag:

```
npm install @formit/nuxt@next
```


This is a duplicate of #383, #385, #375, and #374.

**Comment by nosizejosh** [comment] 2022-09-24 15:01
@justin-schroeder the issue still persists and i'm unable to login to my app because all forms are disabled. 

@Zielgestalt did you have to do anything else other than run npm i @formkit/nuxt@next to get it to work?

**Comment by justin-schroeder** [comment] 2022-09-24 15:05
I just did a fresh install with nuxt RC.11 and `@formkit/nuxt@next` it worked fine. Maybe try removing FormKit and re-installing

**Comment by GustavoFenilli** [comment] 2022-09-24 15:08
Just make sure that the lock changed, otherwise it does not change, removing from the package.json and adding back should fix.

**Comment by nosizejosh** [comment] 2022-09-24 15:10
just tried removing and adding again, but this time using yarn and not npm and that worked. Thanks!

**Comment by Zielgestalt** [comment] 2022-09-24 15:46
Worked for me with pnpm (removing and adding again).

**Closed** 2022-10-20 08:43 UTC
Labels: 🐛 bug-report
