### ISSUE TITLE
Schema: Parenthetical statements with no operator execute string statements

### ISSUE THREAD

**Issue by snoozbuster** [formkit/formkit#857] opened 2023-07-29 00:41 UTC
### Reproduction

https://formkit.link/f7751afff5df25f181e8adb65ceed99c

### Describe the bug

The following two expressions have identical meanings, but produce different results:

```
`(($value) <= ('2023-07-07')) === (false)`
`(($value) <= '2023-07-07') === (false)`
```

In specifics - the first does not evaluate to `true` in any scenario I have tried. The second works as expected. This behavior does _not_ happen for `<` or `>`, but _does_ happen for `>=`. 

In the reproduction, entering `2023-07-08` into the input field should cause all three examples to be shown. However, the middle one does

### Environment

• OS: MacOs
• Browser Edge
• Version latest

**Comment by andrew-boyd** [comment] 2023-07-31 15:07
Ok — simplified the issue. Looks like the schema is doing the math in the second parens and returning `2009` instead of a boolean value for the full expression. Playground here: https://formkit.link/c385706dd201ef5cbb00a0e8392f3313

![Screenshot 2023-07-31 at 11 05 52 AM](https://github.com/formkit/formkit/assets/2946356/c1dd4c27-9723-4185-b74e-c0bca1c93a9e)

**Comment by snoozbuster** [comment] 2023-07-31 17:30
Fascinating. any idea why this only happens with parenthesis and the lte/gte operators?

**Comment by GustavoFenilli** [comment] 2023-07-31 17:37
It also happens for `!=`.

**Comment by snoozbuster** [comment] 2023-07-31 18:59
but then why doesn't it happen for `<` or `>` on their own?

**Comment by andrew-boyd** [comment] 2023-08-01 02:33
Not sure — gotta be something in the schema parser (it’s our own parser, not full JavaScript runtime). We will take a look.

**Comment by justin-schroeder** [comment] 2023-08-08 20:42
This occurs anytime a parenthesis contains only a quoted value with no operands (nothing to do with gt/lt etc). The value is "unwrapped" from the quotes and executed. It’s a wild edge case, but one that should be fixed. Quotes should be respected even on unnecessary parentheticals as in this example.

**Comment by justin-schroeder** [comment] 2023-08-09 14:25
Little update, here is the simplest reproduction:

https://formkit.link/518165d286db1a37e30752a13f18560b

This occurs when a parenthetical statement contains a single string (unnecessarily wrapped in a parenthesis) . In all the examples above a string like `"2021-01-01"` is wrapped directly in a parenthesis `("2021-01-01")` which has no effect, but is tricking the compiler into unwrapping the string and executing it.

**Closed** 2023-08-11 18:57 UTC
Labels: 🐛 bug, 🚀 release-ready, 🟡 priority-2
