### ISSUE TITLE
select input keeps removed option value

### ISSUE THREAD

**Issue by fsoffel** [formkit/formkit#688] opened 2023-05-04 09:10 UTC
### Reproduction

https://formkit.link/e6e9b49c13ce209f6c5f888b581d5105

### Describe the bug

I am using a select input (`<FormKit type="select" ... />`) with a variable list of options. If I select an element from that list which then gets removed from the options and therefore the select list, the display changes to a value which is still an option (this is fine). However, if I submit the form, the removed old value is still sent and not the one displayed in the form.

### Environment

• OS: Docker Container with node:19.8.1
• Browser: Edge

**Comment by sashamilenkovic** [comment] 2023-05-04 11:27
@fsoffel Your playground link seems to only` link to a single text input. Do you have a reproduction of what you are trying to do with the select input you can share?

**Comment by sashamilenkovic** [comment] 2023-05-08 12:34
@fsoffel Sorry, I'm still a little confused (probably just me not following). So in your example, you have an initial options array defined in your setup script with two elements that in the next line you are setting to just one `options = ['first']`. You then are assigning an initial value of "second" to your select input. I see there is also an undefined reference to a "reduce" function, was that meant to be part of your example? 
 
 Here is your code example with my questions posed in the form of comments: https://formkit.link/b63b743b2d60810b5e6b44695c09c119

**Comment by fsoffel** [comment] 2023-05-08 13:17
Sorry, for the messed up code. Here is an update: [https://formkit.link/bff511dd681024001f4d61d0b22eb357](https://formkit.link/bff511dd681024001f4d61d0b22eb357). 
I'll answer your questions here as well: Yes, the idea of the button was to call a `reduce` method which removes the second element from the options array. My expectation would have been that the current value of the select input also changes when I remove the selected option from the options list.

**Comment by sashamilenkovic** [comment] 2023-05-08 13:29
@fsoffel Perfect, thank you for the explanation. So this interesting, I think I would actually expect that the current value of the select input would not change, and in fact, the select input would still display the value "second" (it doesn't which I think is a bug and should be fixed) despite it not having a matching option. Perhaps I'm off base about this though, @GustavoFenilli @justin-schroeder @andrew-boyd do you all have an opinion about this?

**Comment by GustavoFenilli** [comment] 2023-05-08 14:44
Well @justin-schroeder and I talked about this once in the discord and I believe this is not a bug, and it doesn't have much to do with the options there, its mostly because you're setting the `value` manually.

You can use a plugin to change this behaviour like so https://formkit.link/cc238775abcfbaf0b511a38b721f66e4

**Comment by fsoffel** [comment] 2023-05-08 15:09
@GustavoFenilli Thank you for your answer. In my use case I do not manually set the value of the select input but it is selected through clicking. Then the options are changed and the behaviour is the same as in my example. However your suggestion with the plugin is the solution I was looking for. Thanks again.
However, as a User I would expect for the select input (if set) to only have feasible values from the options or to be undefined.

**Comment by GustavoFenilli** [comment] 2023-05-08 15:18
What I meant by manually is that the value is added to the node ( by user clicking an option, manually calling `node.input` ) after that the options change, so the value is still set to what was clicked, as the options do not call input.

There is also the possibility of when changing the options, to check if the current value is in the new options, if not to call `node.input(undefined)`.

**Comment by justin-schroeder** [comment] 2023-05-18 14:09
Not sure there is anything for us to do here, so I'm closing for now. We do not want to constrain the value to only the available list — perhaps in the future we could publish a plugin for this and link it on the docs.

**Closed by justin-schroeder** 2023-05-18 14:09 UTC
Labels: 🐛 bug-report, ⛑ Needs triage
