### ISSUE TITLE
Type error for attribute that is used to set inital value(value)

### ISSUE THREAD

**Issue by bekjon-me** [formkit/formkit#1311] opened 2024-04-15 15:25 UTC
### Reproduction

https://formkit.link/8a4632b7cc5e6a3ea8505b44dbc70b1e

### Describe the bug

I have code like this code above.  I am setting initial value using value attribute and it is working. But typescript giving error like this
![image](https://github.com/formkit/formkit/assets/84561206/96e06cfb-1023-425b-ac6f-2c4f92002319)

- when I use values attribute instead of value typescript isn't giving any errors, but initial value isn't being setted

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by fenilli** [comment] 2024-04-15 15:30
Can you update the reproduction, you need to click the share button on the top right.

**Comment by justin-schroeder** [comment] 2024-04-15 15:38
@bekjon-me I just tried this and it works fine in VSCode. it looks like you are using WebStorm — we don’t currently have a license to that (just applied for an open source one). Do you know if it is using the latest versions of Vue Language Tools

**Comment by bekjon-me** [comment] 2024-04-15 15:46
``> @bekjon-me I just tried this and it works fine in VSCode. it looks like you are using WebStorm — we don’t currently have a license to that (just applied for an open source one). Do you know if it is using the latest versions of Vue Language Tools

![image](https://github.com/formkit/formkit/assets/84561206/6cb7425a-7cce-4a64-8e4a-c36ede7b2473)

the same for vscode too. here is my package.json
``` json
{
  "type": "module",
  "private": true,
  "packageManager": "pnpm@8.15.5",
  "scripts": {
    "build": "vite-ssg build",
    "dev": "vite --port 3333 --open",
    "lint": "eslint .",
    "preview": "vite preview",
    "preview-https": "serve dist",
    "test": "vitest",
    "test:e2e": "cypress open",
    "test:unit": "vitest",
    "typecheck": "vue-tsc --noEmit",
    "up": "taze major -I",
    "postinstall": "npx simple-git-hooks",
    "sizecheck": "npx vite-bundle-visualizer",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "@unhead/vue": "^1.8.20",
    "@vueuse/core": "^10.9.0",
    "@vueuse/head": "^2.0.0",
    "nprogress": "^0.2.0",
    "pinia": "^2.1.7",
    "vue": "^3.4.21",
    "vue-demi": "^0.14.7",
    "vue-i18n": "^9.10.2",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.8.3",
    "@chromatic-com/storybook": "^1.2.25",
    "@egoist/tailwindcss-icons": "^1.7.4",
    "@faker-js/faker": "^8.4.1",
    "@formkit/icons": "^1.6.0",
    "@formkit/vue": "^1.6.0",
    "@headlessui/vue": "^1.7.19",
    "@heroicons/vue": "^2.1.3",
    "@iconify-json/carbon": "^1.1.31",
    "@intlify/unplugin-vue-i18n": "^3.0.1",
    "@shikijs/markdown-it": "^1.2.0",
    "@storybook/addon-actions": "^8.0.4",
    "@storybook/addon-essentials": "^8.0.4",
    "@storybook/addon-interactions": "^8.0.4",
    "@storybook/addon-links": "^8.0.4",
    "@storybook/blocks": "^8.0.4",
    "@storybook/test": "^8.0.4",
    "@storybook/vue3": "^8.0.4",
    "@storybook/vue3-vite": "^8.0.4",
    "@types/markdown-it-link-attributes": "^3.0.4",
    "@types/nprogress": "^0.2.3",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue-macros/volar": "^0.18.12",
    "@vue/test-utils": "^2.4.5",
    "@vueuse/router": "^10.9.0",
    "autoprefixer": "^10.4.18",
    "axios": "^1.6.8",
    "critters": "^0.0.22",
    "cross-env": "^7.0.3",
    "cypress": "^13.7.0",
    "cypress-vite": "^1.5.0",
    "eslint": "^8.57.0",
    "eslint-plugin-cypress": "^2.15.1",
    "eslint-plugin-format": "^0.1.0",
    "eslint-plugin-storybook": "^0.8.0",
    "gsap": "^3.12.5",
    "https-localhost": "^4.7.1",
    "lint-staged": "^15.2.2",
    "markdown-it-link-attributes": "^4.0.1",
    "pnpm": "^8.15.5",
    "postcss": "^8.4.37",
    "rollup": "^4.13.0",
    "shiki": "^1.2.0",
    "simple-abortable-promise": "^1.1.1",
    "simple-git-hooks": "^2.11.0",
    "storybook": "^8.0.4",
    "storybook-dark-mode": "^4.0.1",
    "tailwindcss": "^3.4.1",
    "taze": "^0.13.3",
    "typescript": "^5.4.2",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-vue-components": "^0.26.0",
    "unplugin-vue-macros": "^2.7.11",
    "unplugin-vue-markdown": "^0.26.0",
    "unplugin-vue-router": "^0.8.5",
    "vite": "^5.2.0",
    "vite-bundle-visualizer": "^1.1.0",
    "vite-plugin-inspect": "^0.8.3",
    "vite-plugin-pwa": "^0.19.5",
    "vite-plugin-vue-devtools": "^7.0.19",
    "vite-plugin-vue-layouts": "^0.11.0",
    "vite-plugin-webfont-dl": "^3.9.1",
    "vite-ssg": "^0.23.6",
    "vite-ssg-sitemap": "^0.6.1",
    "vitest": "^1.4.0",
    "vue-tsc": "^2.0.6"
  },
  "simple-git-hooks": {
    "pre-commit": "pnpm lint-staged"
  },
  "lint-staged": {
    "*": "eslint --fix"
  },
  "eslintConfig": {
    "extends": [
      "plugin:storybook/recommended"
    ]
  }
}

```

> @bekjon-me I just tried this and it works fine in VSCode. it looks like you are using WebStorm — we don’t currently have a license to that (just applied for an open source one). Do you know if it is using the latest versions of Vue Language Tools

**Comment by fenilli** [comment] 2024-04-15 15:57
Firstly there is no such thing as `:values` I believe, so it should indeed be `:value`, alsso it looks like you don't have volar installed, you should install that.

**Comment by bekjon-me** [comment] 2024-04-15 16:09
> Firstly there is no such thing as `:values` I believe, so it should indeed be `:value`, alsso it looks like you don't have volar installed, you should install that.

![image](https://github.com/formkit/formkit/assets/84561206/876d0bdd-b055-4c84-947c-a265894238a8)
this extension is installed, I think volar is deprecated

**Comment by fenilli** [comment] 2024-04-15 16:41
You're correct that the "volar" in itself is deprecated, but it is still the codename for the official vue package `vue.volar`.

also the version seens outdatted, as I have currently 2.0.10 can you try updating it?

**Comment by sashamilenkovic** [comment] 2024-04-22 13:24
@bekjon-me Closing this for now but feel free to reopen or comment back if you're still having issues.

**Closed as completed by sashamilenkovic** 2024-04-22 13:24 UTC
Labels: 🐛 bug-report, ⛑ Needs triage
