### ISSUE TITLE
FormKit element breaks page when using NuxtPage with page transition in Nuxt 3.9

### ISSUE THREAD

**Issue by Gardamuse** [formkit/formkit#1095] opened 2023-12-27 17:58 UTC
### Reproduction

https://stackblitz.com/~/github.com/Gardamuse/nuxt-starter-uy3uwx

### Describe the bug

When a FormKit component is added on a page rendered via NuxtPage, and a pageTransition is set up in nuxt.config, the following warning messages are displayed in the console even though there is a single root node:

```[Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated. ```

```[nuxt] `/pages/index.vue` does not have a single root node and will cause errors when navigating between routes.```

If multiple pages are added and the user tries to transition between them, the page that should be transitioned to is never rendered. (Not part of the reproduction example.)

- [Nuxt page transitions activated like this](https://nuxt.com/docs/getting-started/transitions)
- [FormKit installed as instructed here](https://formkit.com/getting-started/installation#with-nuxt)

### Environment

• OS: Linux
• Browser: Firefox
• Nuxt v3.9.0
• FormKit 1.4.0

**Comment by justin-schroeder** [comment] 2023-12-27 20:26
I think this is just because your page does not have a root element.

**Comment by Gardamuse** [comment] 2023-12-28 05:17
> I think this is just because your page does not have a root element.

Oh. Could you point out where I am missing a root element? Both app.vue and index.vue has a single div at the root which I thought would be enough.

app.vue
```
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```

index.vue
```
<template>
  <div>
    <h1>index</h1>
    <FormKit type="text" />
  </div>
</template>
```

**Comment by justin-schroeder** [comment] 2023-12-29 19:29
When i originally went to the page there was no <div> wrapper in your index.vue. With that in there do you still get errors?

**Comment by Gardamuse** [comment] 2023-12-29 20:22
@justin-schroeder Yes, I receive the error with the current reproduction repo.

**Comment by justin-schroeder** [comment] 2023-12-29 21:46
@Gardamuse I see that now too. I think this is now addressed in the `@next` tag of `@formkit/nuxt`.

**Comment by justin-schroeder** [comment] 2023-12-29 21:51
ok, actually delay on that 😂 more bugs to fix there....

**Comment by justin-schroeder** [comment] 2023-12-30 18:14
Ok this is resolved with `unplugin-formkit@0.2.10` which is now on the `@next` tag of `@formkit/nuxt`

**Comment by root5427** [comment] 2024-01-01 18:06
Facing the same issue even though I'm using `@formkit/nuxt` with the `next` tag. Here is a minimal [reproduction](https://codesandbox.io/p/devbox/formkit-nuxt-transition-zmpn7n)

**Comment by justin-schroeder** [comment] 2024-01-02 16:41
@root5427 yep, there were still some issues, try again with the latest version of next (`1.5.0-6a47acc`) and it should be working better.

**Comment by Gardamuse** [comment] 2024-01-13 06:39
Great, thank you! I can confirm that it works for me now using the `next` tag!

**Closed** 2024-01-17 00:04 UTC
Labels: 🐛 bug, 🚀 release-ready
