### ISSUE TITLE
Nuxt SSG results in runtime error on Safari

### ISSUE THREAD

**Issue by ennioVisco** [formkit/formkit#298] opened 2022-06-26 21:46 UTC
### Reproduction

https://codesandbox.io/s/formkit-nuxt-ssr-minimal-dnikdj

### Describe the bug

The app won't render and returns the following error in the dev tools of Safari:
`SyntaxError: Invalid regular expression: range out of order in character class`

To reproduce, look at the reproduction link, then:

- run `yarn generate`
- run a static HTTP server from the files in `.output/public` (an easy way to do so is to execute `cd .output/public` and then `python -m http.server 8000` if you have python installed, the website should be navigated from safari at http://localhost:8000).

Note that this bug does not appear when running through node (or when executing the `dev` or `preview` commands of the nuxt cli).

### Environment

------------------------------
- Operating System: `Darwin` (Mac OS)
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by justin-schroeder** [comment] 2022-06-27 00:42
@ennioVisco the code sandbox seems to just be a blank nuxt project?

**Comment by ennioVisco** [comment] 2022-06-27 05:58
> @ennioVisco the code sandbox seems to just be a blank nuxt project?

It is. For a minimal reproduction it's sufficient to enable the SSR: false flag.

**Comment by justin-schroeder** [comment] 2022-06-28 18:36
Hmm, unfortunately I'm unable to see the error.

**Comment by ennioVisco** [comment] 2022-06-28 18:45
> Hmm, unfortunately I'm unable to see the error.

@justin-schroeder you cannot see it from the sandbox. Did you follow the instructions? Basically you can try locally by:
- following the formkit nuxt guide, 
- adding the `ssr:false` flag in `nuxt.config.ts` 
- run yarn generate 
- run throw a static web server the folder `.output/public`
It should be a 1-2min setup, but afaik there is no way to make it run in the sandbox without node.

**Comment by justin-schroeder** [comment] 2022-06-28 18:58
Ok thanks, read your report in more depth 😂

I did a local install, did `ssr: false`, generated, served the `./output/public` directory, and opened in Safari (15.2).

![image](https://user-images.githubusercontent.com/1950463/176261086-e04db4ee-a132-4dc1-bdd4-c13e51431e7d.png)


![image](https://user-images.githubusercontent.com/1950463/176261131-f3122dc9-aa80-4251-8114-43578fe0f275.png)

I'm not seeing any errors though. I believe you hahaha — but I just cant see it.

**Comment by ennioVisco** [comment] 2022-06-28 21:10
> Ok thanks, read your report in more depth 😂
> 
> I did a local install, did `ssr: false`, generated, served the `./output/public` directory, and opened in Safari (15.2).
> 
> ![image](https://user-images.githubusercontent.com/1950463/176261086-e04db4ee-a132-4dc1-bdd4-c13e51431e7d.png)
> 
> ![image](https://user-images.githubusercontent.com/1950463/176261131-f3122dc9-aa80-4251-8114-43578fe0f275.png)
> 
> I'm not seeing any errors though. I believe you hahaha — but I just cant see it.

haha that's frustrating. But actually I believe it doesn't give errors because you are using [serve](https://www.npmjs.com/package/serve), which still loads node libraries in the environment (just like the dev environment). Could you try with another static server? If you have python you can use the 1-line I shared, otherwise any PHP/XAMPP or online hosting should be fine, just make sure it is not running in a Node environment.

Btw I'm using Safari 15.5 on ARM M1.

**Comment by justin-schroeder** [comment] 2022-06-29 15:39
Ok — I was finally able to track this down. The only way I could reproduce the bug was using your python server. The issue is that the python server is not setting the charset to utf-8 in the `Content-Type` header on the javascript file responses. So any UTF-8 characters in your JS files die. However `serve` and other servers do return the charset with the content type:

entry.mjs request in python "server" | entry.mjs request using "serve"
----------------------------------------------|---------------------------------------------------
![image](https://user-images.githubusercontent.com/1950463/176477251-06e30819-4ae1-49b5-8935-e80aa6c1d334.png) | ![image](https://user-images.githubusercontent.com/1950463/176477133-f33c8f85-a9fa-45f9-8271-d53d930ac674.png)

FormKit will continue to require UTF-8 support, but if you *really* need to get it working without UTF-8 you can remove the `alpha`, `alpha_spaces` and `alpha_numeric` validation rules from your build by using a custom FormKit configuration (not `defaultConfig`). Currently those are the only places in FormKit where UTF-8 characters are used. However, I cannot guarantee that other UTF-8 characters wont be introduced at some point in the future.

I'm going to close this, but I appreciate you bringing it up, its a new one to me.

**Closed by justin-schroeder** 2022-06-29 15:39 UTC
Labels: 🐛 bug-report

**Comment by ennioVisco** [comment] 2022-06-29 15:44
> Ok — I was finally able to track this down. The only way I could reproduce the bug was using your python server. The issue is that the python server is not setting the charset to utf-8 in the `Content-Type` header on the javascript file responses. So any UTF-8 characters in your JS files die. However `serve` and other servers do return the charset with the content type:
> 
> entry.mjs request in python "server"	entry.mjs request using "serve"
> ![image](https://user-images.githubusercontent.com/1950463/176477251-06e30819-4ae1-49b5-8935-e80aa6c1d334.png)	![image](https://user-images.githubusercontent.com/1950463/176477133-f33c8f85-a9fa-45f9-8271-d53d930ac674.png)
> FormKit will continue to require UTF-8 support, but if you _really_ need to get it working without UTF-8 you can remove the `alpha`, `alpha_spaces` and `alpha_numeric` validation rules from your build by using a custom FormKit configuration (not `defaultConfig`). Currently those are the only places in FormKit where UTF-8 characters are used. However, I cannot guarantee that other UTF-8 characters wont be introduced at some point in the future.
> 
> I'm going to close this, but I appreciate you bringing it up, its a new one to me.

Thanks a lot. Actually the bug came out in production, I assume our server is not using utf-8, thanks for taking care of it!

**Comment by GustavoFenilli** [comment] 2022-06-29 15:46
If you're using python you can use this gist to add utf-8 to the server https://gist.github.com/zakandrewking/df4c94162ac1cf9657ce

**Comment by vortechron** [comment] 2022-07-31 09:01
@justin-schroeder btw i also facing same issue when using formkit with capacitorjs + nuxt3 on ios.. can u show me how to disable those validation rules

FYI, I've manually find and replace those characters and can confirm those rules cause this issues.

**Comment by justin-schroeder** [comment] 2022-08-08 13:42
> @justin-schroeder btw i also facing same issue when using formkit with capacitorjs + nuxt3 on ios.. can u show me how to disable those validation rules
> 
> FYI, I've manually find and replace those characters and can confirm those rules cause this issues.

It would be far better to ensure your server is returning the proper charset header.

**Comment by vortechron** [comment] 2022-08-08 14:32
@justin-schroeder im using capacitorjs on ios simulator, no server involve, load asset locally, can't figure it out, yet. haha

**Comment by justin-schroeder** [comment] 2022-08-08 16:08
maybe you need a meta tag on your page for charset?
