### ISSUE TITLE
Unable to reset form with localstorage plugin

### ISSUE THREAD

**Issue by zgurea1** [formkit/formkit#1089] opened 2023-12-19 13:07 UTC
### Reproduction

https://formkit.link/240690ce7705f58fecdbd2caa8701ad2

### Describe the bug

Hello, when you try to reset the form with the localstorage plugin the file object remains even if you completely delete localstorage.
So after you submit the form it remains in localstorage and is not deleted.

### Environment

• OS: [Windows 10]
• Browser [firefox]
• Version [1.4.0]

**Comment by justin-schroeder** [comment] 2023-12-20 16:41
I’m not seeing this behavior. Can you perhaps give a step-by-step procedure to reproduce it?

**Comment by zgurea1** [comment] 2023-12-21 09:06
Here we fill the form and we see it in localstorage.

![image](https://github.com/formkit/formkit/assets/60965273/d4c80495-f0fe-4f31-99c3-711da823611c)

After you submit the form, localstorage remain.

![image](https://github.com/formkit/formkit/assets/60965273/fa2b76d3-0e61-4073-9597-eb021576463e)

**Comment by justin-schroeder** [comment] 2023-12-29 15:27
I see what you’re saying. I guess I would have a different expectation than you about what should happen here. In my view, the form should reset to it’s initial state which includes the file property`{ file: [] }`) since the the `file` input type should always be set to an array even when empty, and the local storage should always be a reflection of that precise state, even if that state is empty.

I think your expectation is that when a form is "empty" there is no local storage at all, is that correct?

If so then the primary question becomes how we determine what the "initial" or "empty" state of the form is. This is complicated by the fact that some inputs provide initial values, such as the `file` input or multiple checkboxes. Knowing what an "empty" form is becomes rather complex.

Is there any deleterious effect from the local storage existing when the form is in an empty state?

**Comment by andrew-boyd** [comment] 2024-03-07 16:16
Closing — please feel free to re-open if there's an argument against the current behavior.

**Closed by andrew-boyd** 2024-03-07 16:16 UTC
Labels: 🐛 bug-report, ❔needs more info
