### ISSUE TITLE
[schema] submit input won't get disabled

### ISSUE THREAD

**Issue by franzwilding** [formkit/formkit#491] opened 2022-11-28 10:01 UTC
### Reproduction

https://formkit.link/0b4151e2fb86dad1838f42d62763b436

### Describe the bug

When adding a submit button via schema, it will not get disabled. 

When I add the submit button via "actions" prop, everything is working just fine. 

### Environment

• Version [1.0.0-beta.11, 1.0.0-beta.12]

**Comment by dominikklein** [comment] 2022-11-28 11:50
I think this could be a duplicate from: https://github.com/formkit/formkit/issues/236

**Comment by GustavoFenilli** [comment] 2022-11-28 13:54
This is a indeed a duplicate of #236, closing this in favor of it.

**Closed by GustavoFenilli** 2022-11-28 13:54 UTC
Labels: ⑃ duplicate
