### ISSUE TITLE
Pro: Taglist create new tag on Mobile - 'Enter' Key Issue in Multi-field Form

### ISSUE THREAD

**Issue by konstantina90** [formkit/formkit#963] opened 2023-09-25 11:29 UTC
### Reproduction

https://formkit.link/20a202d89d02fed6d00b270f73d73c5d

### Describe the bug

I am trying to setup a taglist input that accepts new tags from the user. It works as expected on desktop but I have some trouble creating new tags when used on mobile devices. 

Hitting 'Enter' takes me to the next field instead of creating a new tag. It did work when taglist was the only field I had in the form.

I have tested this on Firefox mobile and Chrome. On Firefox it works as expected.

You can reproduce the issue by opening the playground link above on a mobile device using a chromium based browser.

### Environment

• OS: Android 12
• Browser chrome
• Version 117

**Comment by justin-schroeder** [comment] 2024-03-05 15:57
So far we’ve been unable to reproduce this. Has it been fixed?

**Comment by sashamilenkovic** [comment] 2024-06-05 17:56
Closing this for now until a reproduction is produced.

**Closed by sashamilenkovic** 2024-06-05 17:56 UTC
Labels: 🐛 bug, 🟡 priority-2, 🔎 reproduction-needed, Pro
