### ISSUE TITLE
[Datepicker] Problem when trying to select year with sequence panel

### ISSUE THREAD

**Issue by apiret** [formkit/formkit#1167] opened 2024-01-31 09:43 UTC
### Reproduction

[Reproduction](https://formkit.com/playground?fkv=latest&fileTab=index.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5BWindex.vueR%3CV*%3CFwmKiG4typeQdJpicker74labelQStarGDJ74min_3XX74max_5XX7*+%2F%3EB%3C%2FVB%27%7Esyntax%21%27L%2CWE.Ufig.jsR9M87ZiUs7B9O8%22.%2FE.theme.jz968%22ZaddonzBexpwGdefaulG%28*pluginsN%5B46%7B%7DY%5DYiUsN%284...M*%29YUfigN%284O*%29B%29L%5D*Bq4*q6creJAutoHeightTextareaPlugin7%5C%278+%29+from+9impwG%28+B%5CnEfwmkitGt+JateL%27%7Eadded%21true%29MgenesisIUsN%3A+OrootClassesQ%3D7R%27%7Eeditw%21%27UconVtemplJ%3EW%28%27name%21%27X-01Y%2C*Z%40E%2F_-dJQ202q++worzs%22B%01zwq_ZYXWVURQONMLJGEB98764*_)

### Describe the bug

I get an error in the console when I add a **min/max date** to the datepicker and want to select years with the panel sequence.

![Screenshot 2024-01-31 at 10 39 49](https://github.com/formkit/formkit/assets/1142871/8b78ebe3-bc54-4048-ab54-2ea35c057332)

### Environment

• OS: [OXS]
• Browser [chrome/firefox]
• Version [chrome version: 121.0.6167.85]

**Comment by justin-schroeder** [comment] 2024-01-31 12:59
duplicate of #1101

**Closed by justin-schroeder** 2024-01-31 12:59 UTC
Labels: 🐛 bug, 🟡 priority-2, Pro
