### ISSUE TITLE
Tailwind genesis copy theme does not round borders

### ISSUE THREAD

**Issue by ddahan** [formkit/formkit#578] opened 2023-02-10 16:10 UTC
### Reproduction

Can't reproduce :(

### Describe the bug

I followed [this documentation page](https://formkit.com/guides/create-a-tailwind-theme) and copy pasted the genesis theme to have a Tailwind version to work with.

It seems to work as expected, except that I have this weird rounding issue on all fields:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/1933516/218137819-cfb1b3c2-fb71-4b1a-b5c3-c9117758403a.png">

I can't reproduce the issue in the playground, which makes me wonder what could cause this in my project. I removed any plugins that could interfere (daisyUI, @tailwindcss/forms, etc.), I removed all custom CSS in tailwind CSS file.

What's _funny_ is that if I add a `rounded` attribute to global->input section in the theme, it seems to solve the issue:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/1933516/218139057-70fead4e-284c-44da-bb50-346bcf05c638.png">

Any idea on what could happen here? Thanks.

### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `routeRules`, `typescript`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.1`, `nuxt-headlessui@1.1.1`, `@dargmuesli/nuxt-cookie-control@4.4.0`, `@formkit/nuxt@1.0.0-beta.15`, `nuxt-icon@0.2.11`
-
Tailwindcss 3.2.4

**Comment by andrew-boyd** [comment] 2023-02-13 14:31
@ddahan Not sure why you're seeing those styles if they're not reproducible in the playground — But the crux of the issue is that your `input` has a background color assigned but does not have rounded borders. This is why adding `rounded` in your Tailwind theme fixes the issue.

FormKit actually uses the `inner` styles to style the input borders and background so that visually the `prefix`, `prefix-icon`, `suffix`, and `suffix-icon` appear to be inside the input fields. So if you have a rounded `inner` but your contained `input` does not and also has a solid background color you'll get the behavior you're seeing in your screenshot.

**Comment by andrew-boyd** [comment] 2023-02-13 15:47
I'm going to close this, let me know if you need anything else regarding this issue. Thanks!

**Closed by andrew-boyd** 2023-02-13 15:47 UTC
Labels: 🐛 bug-report, ⛑ Needs triage
