### ISSUE TITLE
Mask component with `unmask-value` not allowing removal of last character

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#677] opened 2023-04-27 13:26 UTC
### Reproduction

https://formkit.link/92f8620e97082596a7ea2c47e81f0e04

### Describe the bug

(First off, loving Formkit so far! Thanks for the cracking product.)

To the issue: 

When using a mask input with the options in the attached example, removing input from the field results in the final character(s) removed being left in the data.

As a couple of examples:

1) Enter '123456'
2) Use backspace to remove all characters
3) The value remains as '1', the final character deleted

____

1) Enter '123456'
2) Select the text
3) Delete it (backspace, cut, etc.)
4) The value remains '123456'

The mask used is a slight adaptation from the example in ['Running the mask in reverse'](https://formkit.com/inputs/mask#page-container) - in fact, the documented mask has the issue when run with the same options in the playground.

I'd love this to be my fault, so please correct me if you can spot an issue in the playground. I've a feeling it might be a bug in the interplay of the mask and the value's unmasking though?

Worth noting I'm using a schema for my local setup, but I had trouble reproducing that in the playground - both seem to have the issue.

### Environment

• OS: Mac OS Monterey 12.6.3
• Browser: Chrome
• Chrome version: 112
• Formkit version: 0.16.4

**Comment by justin-schroeder** [comment] 2023-04-27 14:19
Thanks for the reproduction. It looks like the issue here is we dont "emit" when the input is fully empty. Even if you remove reverse, remove the repeat, and type in some number `123` and then select all and delete, we leave the value in place.

Good find, we’ll address this 👍

https://formkit.link/4da8f5150ce0b189e42d65c5c3535ed8

**Comment by SDRACK** [comment] 2023-04-27 14:41
Great, thanks @justin-schroeder - appreciate the rapid response. Looking forward to the fix :)

**Comment by justin-schroeder** [comment] 2023-04-27 18:15
This is now fixed in `@formkit/pro@0.111.12`.

**Comment by justin-schroeder** [comment] 2023-04-27 18:22
I spoke to soon

**Comment by justin-schroeder** [comment] 2023-04-27 19:22
Ok haha. Fixed in `@formkit/pro@0.111.14` :)

**Closed by justin-schroeder** 2023-04-27 19:22 UTC
Labels: 🐛 bug, 🟡 priority-2, Pro

**Comment by SDRACK** [comment] 2023-04-28 09:06
Brilliant, thanks very much for the speedy patch @justin-schroeder 🙌 

(Incidentally, found a hacky fix using `prefix: '\u2028',`, but am happy I don't need to push that anywhere :D)
