### ISSUE TITLE
Field IDs beginning with numbers not valid

### ISSUE THREAD

**Issue by matthewbecker1990** [formkit/formkit#1369] opened 2024-05-22 02:00 UTC
### Reproduction

https://discord.com/channels/793529058377072650/940340536747896842/1242656373976858634

### Describe the bug

As discussed here: https://discord.com/channels/793529058377072650/940340536747896842/1242656373976858634

Field IDs such as a UUID like ```4c37f9de67a44452813306ebb984674f``` are not valid and cause the error:

``` SyntaxError: Element.closest: '#4c37f9de67a44452813306ebb984674f_popover' is not a valid selector ```

This appears to be happening with Date and Repeatable fields.

### Environment

• Version - Pro 0.125.7

**Comment by andrew-boyd** [comment] 2024-05-22 13:26
Yeah, this is an annoyance. From what I inderstand this is because the HTML spec now says that IDs starting with numbers and containing symbols such as `.` are valid — but that didn't always use to be the case. So traversal and selector methods such as `.closest()` or `querySelectorAll` fail when you use valid IDs. 🤦‍♂️

We've ended up fixing a similar issue with the Datepicker popover by changing an `id` selector to an attribute selector. so:

`#4c37f9de67a44452813306ebb984674f_popover`

becomes:

`[id="4c37f9de67a44452813306ebb984674f_popover"]`

Less performant on the lookup, but necessary I think.

Are you certain you're running the latest version of Pro? Would you mind sharing a Playground reproduction that shows the issue in action on the latest version? That will be very helpful when we loop around to close this one out.

**Comment by justin-schroeder** [comment] 2024-05-22 13:36
FWIW — if the rest of the FormKit team wants to allow ids to start with numbers I wont aggressively fight against it — however I do think this is just generally a bad practice and not something I feel we should explicitly support. Many tools/apps/sites break when you use ids that start with numbers — including basic things like css selectors.

**Comment by fenilli** [comment] 2024-05-22 15:53
So according to mdn:
> For example, . has a special meaning in CSS (it starts a [class selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors)). While valid, unless you are careful to escape it when used as part of a CSS selector, it won't be recognized as part of the element's id. The same applies to the [querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) and [querySelectorAll()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) parameters, which use the same selector syntax. It is easy to forget to do this, resulting in bugs in your code that could be hard to detect.

> Similarly, an id starting with a digit (E.g., 1234-322-678) or a hyphen followed by a digit (E.g., -123), though valid in HTML, may lead to problems when used in CSS, JavaScript, and Web APIs:

So I would say I also don't believe its a fix of our part, ids that do not start with chars are not recommended.

**Comment by fenilli** [comment] 2024-05-22 15:56
With all of that in mind we could add to inputs that rely ( or all inputs for that matter ) just a warning if the ID is not valid when used.

**Comment by sashamilenkovic** [comment] 2024-05-24 11:43
Team has decided we will not be supporting IDs that lead with numbers.

**Closed by sashamilenkovic** 2024-05-24 11:43 UTC
Labels: 🐛 bug, 🔵 priority-3, Pro, datepicker
