### ISSUE TITLE
Programatic opening of dropdown does not work in a browser

### ISSUE THREAD

**Issue by LeonDixon** [formkit/formkit#1118] opened 2024-01-12 14:42 UTC
### Reproduction

https://discord.com/channels/793529058377072650/940340536747896842/1195371486647697479

### Describe the bug

When trying to emulate a click on the dropdown input, it does not trigger the options to open and only will show the focus blue outline (If using the regenesis styles). The end shows the option poping up as I pressed 4 to force the option to appear. 

### Environment

• OS: MacOs
• Browser: Chrome
• Version 1.4.0

**Comment by justin-schroeder** [comment] 2024-01-12 16:14
I think the central issue here is the vitest does not have a true browser and thus fires events slightly differently than an actual browser. These cases are already well handled by FormKit Pro’s tests (focus to open) by using browser based testing with playwright. In that vein there’s not much I think we want to change about how these events work in the production code just so faux dom’s interact differently.

As for the iframe issues, this is due to the browser’s behavior around what "focus" means. When you are in the dev tools the iframe is not focused and cannot have true focus. This is why you get a "half focus" (blue ring). No actual focus event is fired until the iframe itself is the active document (not the active document in the dev tools, the active document in the browser’s context). This should never be an issue for users since they actually click or tab into those inputs. Again, not something I think we can fix for this.

That said, if you want to test in your app that, for example, the correct options have been rendered in the dropdown, you can force it open/closed:

```js
getNode('dropdownId').props.expanded = true
```

**Comment by GerryWilko** [comment] 2024-01-15 11:19
Also here is a video showing this does not work. This is within the playground but I can also replicate this behaviour outside of the iFrame

Uploading Screen Recording 2024-01-15 at 11.15.02.mov…

**Comment by sashamilenkovic** [comment] 2024-01-15 12:29
@GerryWilko So let me just narrow down this conversation to address this:

> but this issue can be replicated in Playwright and normal browsers (Chrome & Firefox).

I agree that the dropdown click event cannot be tested via. dev tools in a browser. This is because the dropdown click event handler has a return early condition if the event detail is equal to 0: https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail (which I explained in Discord). An actual click on the DOM _does_ trigger the correct event detail, while trying to get the DOM element via dev tools and programatically clicking does _not_ produce an event with detail equivalent to 0.

This however isn't an issue for browser-based testing suites like Playwright or Cypress. Most tests for the dropdown, autocomplete, and taglist inputs are written using Playwright where we are able to trigger click events just fine without any extra configuration. If you're having an issue with that, the next step would be to see a reproduction.

> Also here is a video showing this does not work. This is within the playground but I can also replicate this behaviour outside of the iFrame
> 
>  Screen.Recording.2024-01-15.at.11.15.02.mov


"If you change the scope in your console to the iframe which renders the vue instance" You are not doing this in this video example, but even if you were, it would not work (based on my response about event detail property above).

Hopefully that cleared some things up! And if not, looking forward to your reproduction of this not working in Playwright so we can get this resolved.

**Comment by GerryWilko** [comment] 2024-01-15 13:16
I see this makes more sense thank you for the detailed explanation. Right we do have a bit of a complex input which calls off to our apis to do an address lookup then renders an address list to select from. It must then be that this issue is related to some other part of this.

Let me work with Leon and put together a reproduction and get back to you.

Thanks again!

**Comment by sashamilenkovic** [comment] 2024-01-24 14:03
@GerryWilko I'm going to close this for now, but go ahead and respond if you are able to create a reproduction.

**Closed by sashamilenkovic** 2024-01-24 14:03 UTC
Labels: 🚫 wontfix
