### ISSUE TITLE
Regression in bundle size for i18n files in v1.5

### ISSUE THREAD

**Issue by gbyesiltas** [formkit/formkit#1139] opened 2024-01-22 11:21 UTC
### Reproduction

https://stackblitz.com/edit/github-wje2vn-ysnjav?file=app.vue,package.json,formkit.config.ts

### Describe the bug

Updating from Formkit 1.4.0 to 1.5.1, I noticed that the bundle size for `formkit/i18` imports are significantly higher, increasing the entry bundle size of our project by about 60kb gzipped, and 350kb ungzipped. 

See screenshots for 1.4.0 vs 1.5.1:
![formkit 1 4](https://github.com/formkit/formkit/assets/50772478/e2c3557b-b9fb-4987-a035-955e07beb665)
![formkit 1 5](https://github.com/formkit/formkit/assets/50772478/49d0b614-9d36-436a-abcd-38f7fe24a5a2)

### Environment

• OS: MacOS
• Browser: N/A

**Comment by justin-schroeder** [comment] 2024-01-25 14:46
Hmm, definitely worth looking into. We change our build tooling for 1.5 so its possible some of the tree shaking got caught up in it.

**Comment by bay007** [comment] 2024-01-25 19:28
Formkit is an awesome library, thanks for it

I am optimizing my SPA, i have watched my final bundle size, its about 700kb, visualizing the bundle i can see @formkit/i18n package is about 500kb :o, i am using formkit 1.5.0, i am currenty using import { en } from "@formkit/i18n"; in my defaultConfig

I don't know if it is an issue or it is a misconfiguration in vite.config.js

Any suggestion will be appreciated. 🙂

![image](https://github.com/formkit/formkit/assets/8164038/f43d6ac4-30d2-45cd-886d-32f7bd24b3f6)







I just watched another project with formkit version "@formkit/vue": "0.18.4" and the size of i18n is good.
![image](https://github.com/formkit/formkit/assets/8164038/d305e3b7-0844-4e78-af6b-852868992e74)

**Comment by gbyesiltas** [comment] 2024-01-25 21:16
Hey @bay007 I'm pretty sure this happened in the latest version(s). If you use 1.4.0 for now it should be drastically lower :)

**Comment by justin-schroeder** [comment] 2024-01-25 21:17
Yeah we’re looking into this, should be fixed relatively soon

**Comment by bay007** [comment] 2024-01-25 21:32
> Hey @bay007 I'm pretty sure this happened in the latest version(s). If you use 1.4.0 for now it should be drastically lower :)

You right, this is my final bundle with 1.4.0 formkit version

![image](https://github.com/formkit/formkit/assets/8164038/d53271fa-5f89-4cef-ad62-292d34f61303)

thanks for the workaround.

**Comment by justin-schroeder** [comment] 2024-01-26 03:16
Goodie — found out this is some kind of fundament limitation in the way esbuild bundles its re-exported dependencies in a non-treeshakable way: https://github.com/evanw/esbuild/issues/1420

Looks like a bit a refactoring work but we should be able to get the code back on track.

Until this is resolved if bundle size is a concern pin 1.4.0

**Comment by justin-schroeder** [comment] 2024-01-29 22:37
This is fixed in 1.5.3 — still a bit of work to be done on tree-shakability of the icons package, but overall this should be muuuuuuuch better.

**Closed by justin-schroeder** 2024-01-29 22:37 UTC
Labels: 🐛 bug, 🔴 priority-1

**Comment by bay007** [comment] 2024-02-01 18:22
@justin-schroeder , i can confirm a downsize with 1.53 version
![image](https://github.com/formkit/formkit/assets/8164038/17cb2167-eda2-4975-bd8c-6e4c4bbed19b)


Thank you

**Comment by riderx** [comment] 2024-07-12 20:22
I see one big part of the space used comes from the theme, could the vite plugin cleanup the theme file and remove all unused component definition?
