### ISSUE TITLE
taglist behavior with empty options

### ISSUE THREAD

**Issue by ericvandever** [formkit/formkit#586] opened 2023-02-14 16:29 UTC
### Reproduction

https://formkit.link/b0e18accf0b6e9f7e00b68f10e46490b

### Describe the bug

While trying to use a taglist as a user-entered only input component (no selectable options), I had issues with the input's behavior.

While the documentation states that the default for options prop is [], it appears to be null as the component throws errors when entering values.

Oddly, when explicitly setting the options to [], the component becomes disabled.

I'm able to mostly satisfy my use-case by setting the options to [''] and hiding the dropdown indicator.

### Environment

• OS: macOs 13
• Browser chrome
• Version 109

**Comment by sashamilenkovic** [comment] 2023-02-14 16:45
@ericvandever The taglist should default to an empty array if no options are passed, that should be fixed. Rendering the taglist disabled when an empty array was passed to options was intended to be a feature for the dropdown family inputs (dropdown, autocomplete, and taglist), but perhaps it makes sense not to do that with the taglist when you're using the "allow-new-values" prop. Your solution to use [''] works, you could also pass the options a function and return an empty array: https://formkit.link/bb067fdfc72d69a9ef119e5a74f9a0ba. 

But yeah. I think your use-case where you're using the taglist just for data entry is a valid one we should consider. Maybe we could add a prop that removes the listbox entirely, hides the dropdown selector, and maybe some more features I can't think of right now?

**Comment by jerrebm** [comment] 2023-03-17 12:42
I've run into the same problem. I want to use the taglist input for custom user-defined values and also load existing values if the user already saved some. But when I set `:options=[]`, the field gets disabled.

Here's a workaround that works for me:

```js
const options = ref(['option-1', 'option-2'])

setTimeout(() => {
    options.value = () => []
}, 100)
```

This lets me add initial values to the taglist input without the field getting disabled and without the listbox showing up.

The only issue left is that if a user types in a value that's already there, the input will remove it. Without the listbox for visual feedback, I'm worried this might confuse users when they're adding a bunch of values. It'd be cool to have an option that just ignores duplicates instead.

**Comment by sashamilenkovic** [comment] 2023-03-17 13:36
@jerrebm Here is a workaround for now: https://formkit.link/c38daa022e445104ebbbefa507276c71. Hopefully in the future we can implement a specific prop that ignores duplicates as you suggested and is more tailored for user-entered values.

**Comment by Youhan** [comment] 2023-06-29 00:17
My use case is very similar. Initially, options are empty but the user will add tags. I don't need a listbox at all. I am using it to collect an array of names as authors of an article.

**Comment by sashamilenkovic** [comment] 2023-06-29 23:46
@Youhan I plan to get out a prop that allows for this behavior, hopefully sometime next week.

**Closed** 2023-08-11 19:51 UTC
Labels: 🐛 bug, 🪄 enhancement, 🚀 release-ready, 💡 needs ideas, 🔵 priority-3, Pro
