### ISSUE TITLE
File input not resetting correctly

### ISSUE THREAD

**Issue by yuelongh** [formkit/formkit#1429] opened 2024-06-26 16:26 UTC
### Reproduction

https://formkit.com/inputs/form

### Describe the bug

I am having the same problem described in the [ticket](https://github.com/formkit/formkit/issues/762) with the version of 1.6.5
so I can reproduce the error by modifying the examples in https://formkit.com/inputs/form

```vue
<script>
export default {
  data() {
    return {
      complete: false,
    }
  },
  methods: {
    async handleSubmit() {
      // Our api request:
      await new Promise((r) => setTimeout(r, 1000))
      this.complete = true
      this.$formkit.reset('myForm')
    },
  },
}
</script>

<template>
  <FormKit type="form" id="myForm" @submit="handleSubmit">
    <h2 class="text-xl font-bold mb-2">Newsletter</h2>
    <p class="text-base mb-4">When this form is submitted the form is reset.</p>
    <div class="success" v-if="complete">Submitted successfully!</div>
    <FormKit
      name="email"
      validation="required|email"
      label="Email address"
      help="What email address would you like to receive our newsletter at?"
    />
      <FormKit
       type="file"
      name="file"
      validation="required"
      label="aaaaa"
         />
    <FormKit
      type="radio"
      name="email_pref"
      label="Email frequency"
      validation="required"
      help="How often should we send you a newsletter?"
      :options="{ daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' }"
    />
  </FormKit>
</template>
```

### Environment

• OS: Mac 13.2.1 
• Browser chrome
• Version 1.6.5

**Comment by justin-schroeder** [comment] 2024-06-27 02:17
Thanks! This is a duplicate of #1249.

**Closed by justin-schroeder** 2024-06-27 02:17 UTC
Labels: 🐛 bug-report, ⛑ Needs triage
