### ISSUE TITLE
Error thrown by `normalizeOptions` when options are null / undefined

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#781] opened 2023-06-21 10:01 UTC
### Reproduction

https://formkit.link/fd53b79a98c060a1e2fcddfa7a147fef

### Describe the bug

We're seeing an error thrown by `normalizeOptions` in `@formkit/pro/node_modules/@formkit/inputs/dist/index.cjs` when `options` is undefined / null.

>[Vue warn]: Error in watcher callback: "TypeError: Cannot convert undefined or null to object"

The issue is caused by this code:

```
    return Object.keys(options).map((value) => {
        return {
            label: options[value],
            value,
        };
    });
```

Specifically, this is caused by attempting `Object.keys(null)`.

Adding a guard clause seems to resolve the issue, e.g.

```
    if (!options) { return []; }

    return Object.keys(options).map((value) => {
        return {
            label: options[value],
            value,
        };
    });
```

The start of the function is already wrapped in a check (`if (Array.isArray(options)) {`), so is it possible the `mapping` also needs this?

Unfortunately, I've not been able to replicate this - the only pro inputs we're using at the moment are `autocomplete`, `datepicker` and `repeater`, and the playground I've attached doesn't seem to throw this error no matter what I put in there.

The section of our schema that causes this (included in the playground), doesn't seem to have anything pro nor anything unusual about it.

I'm interested to hear if this is something that you're able to reproduce, whether it's an area some defensive code would be useful, or whether it's likely a mistake our end. Thanks in advance :)

Edit:

A bit more digging, and it seems the error is thrown specifically where we have an `if:` condition relating to the schema item. Not always - in our case a few occasions out of a few dozen uses - with nothing distinguishing them from other fields. We've had another issue (not yet raised) where a conditional field is replaced with a different field indeterminately - speculating, but could it be a Vue `key`ing issue?

### Environment

• OS: Ventura 13.3.1 (a)
• Browser Chrome 114.0.5735.133
• Version
"@formkit/icons": "^0.17.2",
"@formkit/pro": "^0.112.6",
"@formkit/themes": "^0.17.2",
"@formkit/vue": "^0.17.2",

**Comment by sashamilenkovic** [comment] 2023-06-21 14:46
@SDRACK The options prop is required for the autocomplete input to work (this should be mentioned in the docs) and the options should be in one of these formats: https://formkit.com/inputs/autocomplete#defining-options. We will be releasing an update to the dropdown family inputs that will set a console warn if the options prop is invalid. 

Do you ever run into this normalizeOptions error when the options you are assigning to your autocomplete isn't null?

**Comment by SDRACK** [comment] 2023-06-21 15:21
Thanks for the quick response @sashamilenkovic - we're never setting them to null as far as I can see. Our implementation has us using an async call to the Google places API, but we fall back to an empty array if we don't get a successful response.

I've a feeling that might be a red herring here, and the real issue comes from something lower level - the error seems to be thrown sometimes (not always) when we've an `if:` condition in the schema. When the bugged condition becomes true, we see the error thrown.

I've copied the fields over from our code (under the comment `// our section throwing the error`) but it doesn't throw anything in the playground.

Adding a guard before `Object.keys(options)` fixes our issue and gets the `if:`s working, but I wonder if the root cause comes from something deeper into the config (pro / not pro, Vue `key`s or something) that I can't control in the playground.

**Comment by sashamilenkovic** [comment] 2023-06-21 17:23
@SDRACK Ok, gotcha. Just curious, in your dev environment, are you also setting the options as object literals? I wonder if you restructure them into a different format if it will work correctly.

**Comment by sashamilenkovic** [comment] 2023-06-21 17:31
We can add an additional guard to the options hook you are referring to, I just want to narrow down what the exact issue is.

**Comment by henryaj** [comment] 2023-06-22 14:02
Thanks for the assistance @sashamilenkovic – I'm the CTO where @SDRACK works and we're keen to get this resolved as soon as possible as it's blocking our (eagerly-awaited!) upgrade from Vue Formulate to FormKit. Let me know if there's anything you need from us to help debug further.

**Comment by justin-schroeder** [comment] 2023-06-22 14:06
@henryaj a reproduction is all we need 👍

We *can* add a guard to "fix" this, but this is a bit silly since passing incorrect data into props will cause errors on almost all props. Adding guards for incorrect data on all props would bloat the package significantly.

**Comment by SDRACK** [comment] 2023-06-22 18:03
Hey @justin-schroeder - I _think_ it's down to scale of our form. As far as I'm aware, we're not passing any incorrect props. We've got some examples where radios are coming through as textboxes and vice versa (e.g. below), so it's very hard to tie down. However, this error is almost always present.

![Screenshot 2023-06-22 at 16 37 54](https://github.com/formkit/formkit/assets/8395303/caa9c416-9dfc-4fdb-b702-5cb706aec50c)
![Screenshot 2023-06-22 at 16 31 58](https://github.com/formkit/formkit/assets/8395303/685fcfac-8ba7-454e-b263-b09d96245e6c)
![Screenshot 2023-06-22 at 16 31 32](https://github.com/formkit/formkit/assets/8395303/785aecf2-a31d-4a8a-913e-6d4c18b16581)

We've actually plugged the guard in manually our end and it's seems to lessen the issue but doesn't resolve it entirely. Instead, using Vue dev tools, we see `options: '[object Object]'` or similar - these are hard coded options, provided directly in the schema, so it doesn't make sense as far as I can see.

I've copied our schema and formdata in the playground and can actually reproduce the issue, but... the share button stops working, presumably due to the size. We're working with a schema with 49 top level keys, and formData with 60 (that's not counting anything nested). 

Here's a screenshot of the issue showing up in the playground:

<img width="1512" alt="Screenshot 2023-06-22 at 18 20 29" src="https://github.com/formkit/formkit/assets/8395303/7ca7019f-dd87-4ee4-ae21-fac2adb7d55a">

I'd be open to it being a fault our end, but seeing it in the playground and with an error originating from Formkit makes we worry it's an issue of scale, and race conditions, key clashes, something else causing the bugs we're seeing.

I'll talk to @henryaj tomorrow about whether we'd be able to provide our real schema and some dummy formData tomorrow morning if you'd be willing to talk via a private channel?

Once again, thanks to both of you @justin-schroeder and @sashamilenkovic for your work on this so far - been banging my head against this one all day today :)

**Comment by justin-schroeder** [comment] 2023-06-22 18:13
I’m certainly *not* saying there isn’t an issue the FormKit library — it could be there 100%, but without a reproduction its stabbing in the dark. We‘ve got thousands of tests that check out so when these issues arise its incredibly hard to help without seeing a reproduction.

There is nothing specific about "scale" that would cause an issue like this other than it is harder to find what is really going on — however — `keys` yes! Vue recycles DOM nodes in fragments if keys are not found and this can lead to unpredictable results. If you are using conditional fields you should place a `key` (this is the vue key) on anything that is dynamic:

```ts
{
  $formkit: 'text'
  if: '$foobar'
  key: 'uniqueKey'
}
```

That said hearing you say you’re seeing this: `options: '[object Object]'` makes me think the options are being provided in some specific way that is breaking it, not sure on whose end. If you want to just send a DM on discord with the code to put in the playground we can help from there.

**Closed** 2023-06-30 16:02 UTC
Labels: 📙 documentation, 🔎 reproduction-needed, Pro
