### ISSUE TITLE
Validation stop firing when custom rule used together with another rule (don't know if just in the described context)

### ISSUE THREAD

**Issue by fabiobulgarella** [formkit/formkit#1371] opened 2024-05-22 09:01 UTC
### Reproduction

https://formkit.link/bb3a2667b5f23695664de9ce0fa1214d

### Describe the bug

Hello,
I've a strange problem with custom rules: when using a global registered custom rules together with an input prop registered custom rule, they stop working with a strange behaviour. Used individually they work as expected.

**Details:**
I have two inputs:
- a Select Input ("Address Mode" with two options ["Static IP", "Public IP"])
- a Text Input ("IP Address").

Using the Select Input I choose which type of IP address will be used on a specific environment.
If "Address Mode" is "Static IP", "IP Address"field is required and must be a valid IPv4 address; if "Address Mode" is Public IP, "IP Address" is disabled and its value is set to undefined by a commit event configured to "Address Mode" input.

The "IP Address" input field has two validation rules applied:
- addressRule, which check if the field is required based on the value of "Address Mode";
- ipv4, which check for IP correctness.

Trying to use the form, I notice that if "Address Mode" is untouched, the two validation rules are correctly applied. But, if I change the value of "Address Mode" to Public IP, then addressRule correctly fire but after that no other validations are performed on the following input changes.

It is worth to note that if the ipv4 rule is removed, everything works as expected.
I also tried to switch the ipv4 rule with another rule (the embedded email rule), and the strange behaviour comes again.

If instead I remove the commit event:
```
onMounted(() => {
  getNode('addr_mode').on('commit', ({ payload }) => {
    if (payload === AddrMode.PUBLIC) {
      getNode('address')?.input(undefined);
    }
  });
});
```
in order to remove any sort of forced mutation (the IP Address field which is set to undefined), the validation continue to fire only if the "IP Address" field is modified before changing the "Address Mode" select field, but only when "Address Mode" return to the Static IP value (rules are not fired when Public IP is selected).

I hope I covered all the cases. Willing to look into the issue further.
Thank you!

### Environment

• OS: MacOS 14.5 (Apple Silicon)
• Browser: Chrome 125.0.6422.61
• Version: @formkit/vue@1.6.3

**Comment by justin-schroeder** [comment] 2024-05-25 02:08
I was able to isolate this and reproduce it. It is a bug.

**Comment by justin-schroeder** [comment] 2024-05-28 17:42
This is fixed in 1.6.4 — thanks for the reproduction 💪

**Closed by justin-schroeder** 2024-05-28 17:42 UTC
Labels: 🐛 bug, 🔴 priority-1

**Comment by Stiropor** [comment] 2024-06-05 13:04
Somehow after this fix my validation stopped working:
1. I have a custom validator, that makes the field required when status is 1
2. when I click submit validator works. But when I change the status, it makes no difference, error stays
3. if I then change the status to unpublished, it works ONLY if I enter something in title and then delete (so it triggers the validation). Somehow status stopped working due to changes in listeners change in the commit.

There are 2 groups with same name, I know, but for a reason (some fields are translatable and get transformed into groups so we can switch and show/hide them). This works perfectly fine for months, form value and all that. Well, so did this rule until 1.6.4 was done.

Is there ANY way I get that node.at actually reacting to status field change? Note that when there are 2 languages there are 2 fields with name status, each in it's own group, that's why the call for `$root.translations.en`.
I'd do it without groups but sadly we cannot name elements like `translations.es.title` and make it work as object, so this was the only option.

Reproduction: https://formkit.link/eade881392843ffc606cf62a1af24bb4

**Comment by justin-schroeder** [comment] 2024-06-06 16:24
Hey! Unfortunately that validation rule was only working due to a bug in prior versions that caused rules to run more often than they should. The only reason this doesnt currently work is that there are 2 groups with the same name. Here it is working fine when they are grouped:

https://formkit.link/8c4094cc5c88ba4f880123891f9d17f8

I understand the rational behind why you need that, however groups by the same names just wont work. Alternatively you could directly assign nodes to a group by using the `parent` prop.
