### ISSUE TITLE
Datepicker returns `dirty` with an initial value in `<script setup>`

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#844] opened 2023-07-21 13:14 UTC
### Reproduction

https://formkit.link/ba56ab8e550cd5204bbb36660d27c908

### Describe the bug

Thank you for the amazing work 🚀 

I noticed that the Datepicker component returns `dirty` with an initial value in `<script setup>`. I'm not sure if is something I should be doing in a more "Formkit way".

Thank you once again 🙏 

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment] 2023-07-21 13:36
Ok, this is an interesting one. Strictly speaking it is true that the form is dirty, so I think I need to leave this as "wontfix", but we should provide some additional utilities to make this easier — like a function `today()` — I’ll create a new issue for that. Here’s what is going on.

The datepicker (by default) outputs a string in ISO3601 format. It automatically sets itself to midnight in of the selected day. So when you provide `new Date()` as the initial value, it modifies the value to something like `2023-07-21T04:00:00.000Z`. This makes the input dirty. Now if you provide an ISO string with a properly truncated date (no microseconds and set to the timezone of the user, or your input is configured to a specific tz and you match that) then it will not be dirty because no mutation to the original value is necessary. For example:

https://formkit.link/5fa52867cab69ddb8d1fca8ff20a427a

**Comment by Tragio** [comment] 2023-07-28 10:33
@justin-schroeder I took your playground and change it to another date. From this `2023-08-01T00:00:00.000Z` to this `1954-10-07T00:00:00.000Z` and it gets dirty.

If the day is 1954-10-03 it is not dirty, but then if I go to the day after, 04 it gets dirty 🤔

**Comment by Tragio** [comment] 2024-04-16 20:48
Hi @justin-schroeder 👋,

Did you get a chance to take a look at this weird scenario? 😅 

cc: @andrew-boyd

**Comment by fenilli** [comment] 2024-04-17 15:19
I looked at the link and changed to `1954-10-07T00:00:00.000Z` and it is not dirty, anything I need to do to reproduce outside of that?

**Comment by justin-schroeder** [comment] 2024-04-17 15:23
@fenilli its flakey, lots of dates it does not return dirty, but some it does. I think it has to do with the users timezone.

@Tragio short answer: no, sadly I have not had time to look into this further, but its still on the list 👍

**Comment by sashamilenkovic** [comment] 2024-06-03 17:56
> @justin-schroeder I took your playground and changed it to another date. From this `2023-08-01T00:00:00.000Z` to this `1954-10-07T00:00:00.000Z` and it gets dirty.
> 
> If the day is `1954-10-01` or `02` or `03` it **doesn't** get dirty, but then if I go to the day after, `04` it gets dirty 🤔
> 
> https://formkit.link/11676a7dd2512ad0a2aa096ce9eb0379

This should be resolved at FormKit Pro v0.126.6

**Closed by sashamilenkovic** 2024-06-03 17:56 UTC
Labels: 🐛 bug, 🟡 priority-2, Pro
