### ISSUE TITLE
Inline `validation-rules` object causes constant invalidation of previous rules.

### ISSUE THREAD

**Issue by MortenHe** [formkit/formkit#514] opened 2022-12-21 09:34 UTC
### Reproduction

https://formkit.link/b326aedb461d5c97e891973cf84f0340

### Describe the bug

I'm trying to create a form that contains an input with custom validation. I used the example code from here: 
https://formkit.com/essentials/validation#debounce-milli#debounce-milli

The submit button should be disabled until the form is valid. I used the example code from her:
https://formkit.com/inputs/form#validity-state#validity-state

When I open the Chrome Dev tools I get the repeating error
"Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked at index.mjs:169:18"

Is it my fault or a bug?

Thank you in advance and Merry Christmas to you all!

### Environment

• OS: Windows 10 Pro
• Browser chrome
• Version 108

**Comment by justin-schroeder** [comment] 2022-12-21 15:10
Great question — it does look like there was a regression in beta 12 — we added support for dynamic validation rules via the `validation-rules` prop — unfortunately, when you define objects "inline" (`:prop="{ someValue }"`) Vue sees these as "new" prop values on every iteration (since `{} !== {}` in JavaScript). This means whenever you type and a re-render is performed FormKit is invalidating the previous rules. Doh!

The workaround is easy enough — you just define your rules object in your setup block: https://formkit.link/478716df589caa9a1622f9b91eb295ed

However, I'm going to mark this as a bug so we can make sure this stumbling block doesn't occur in the future.

**Comment by MortenHe** [comment] 2022-12-22 16:04
Thank you, Justin! It works 💪 

That was a very nice experience for my first answered Github issue ever 😄

**Comment by justin-schroeder** [comment] 2022-12-22 16:09
Great! I'll leave this open so we’ll remember to work on making this better.

**Comment by justin-schroeder** [comment] 2023-01-17 18:54
This is fixed in `release/beta.13` — will be published in the next release.

**Closed** 2023-01-19 21:11 UTC
Labels: 🐛 bug, 🚀 release-ready, 🟡 priority-2
