### ISSUE TITLE
Disabled form on submit not working when also using disabled prop

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#184] opened 2022-04-01 08:24 UTC
### Describe the feature

At the moment it's not possible to have the default submit "disable" behaviour together with the usage of the disabled prop: https://formkit.link/db499754afec2981448b26b5a932be63

In the code, it looks like this is the expected behaviour, but maybe we can at something that the default behaviour is also working in this situation?

**Comment by tosling** [comment] 2022-04-09 09:15
Hi @dominikklein, 

with "default submit 'disable' behaviour", you mean showing the loading spinner and disabling the button (and styling it grey, in Genesis theme)?

If I look at your reproduction link (with MacOS, Chrome 100), it seems that the disabling is working correctly, just the button is not greying out. Which for me looks like a styling issue, and could be related to #195.

**Comment by dominikklein** [comment] 2022-04-11 11:11
No I mean the fields should be disabled, this is not the case in the described situation.

**Comment by tosling** [comment] 2022-04-11 11:53
Hmm, then I don't get what exact behavior you expect.

on your example:
* if `disabled == false` -> the whole form is accessible.
* if `disabled == true` -> the input and button is disabled. 

That sounds about correct for me.

**Comment by andrew-boyd** [comment] 2022-04-13 14:27
Hey @dominikklein - trying to understand this one. In your example provided the `disabled` prop is bound to a `ref` that's set to `false` and never changes. Toggling it to `true` and then back to `false` during your submit handler and subsequent timeout seems to have the effect you're looking for if I understand what your issue correctly.

https://formkit.link/cdafa43e77bd0d404570ba28bc45de57

**Comment by justin-schroeder** [comment] 2022-05-04 16:53
Closing this one in favor of #215

**Closed by justin-schroeder** 2022-05-04 16:53 UTC
Labels: 🪄 enhancement
