### ISSUE TITLE
Error when using tab in DatePicker

### ISSUE THREAD

**Issue by vmitchell85** [formkit/formkit#827] opened 2023-07-11 17:27 UTC
### Reproduction

https://formkit.link/2ee1e0b3644c888b6e4d330a10ab7f7f

### Describe the bug

When using a `datepicker` element without `time` included hitting the `tab` key within the picker throws a JavaScript error.

See a demo here: https://d.pr/v/O9a2RY

I posted about it [on Discord](https://discord.com/channels/793529058377072650/1025447518617735210/1128368897863733318) already and was told to create an issue.

### Environment

• OS: MacOS
• Browser: Chrome
• Version: 114.0.5735.198

**Comment by mhuijser** [comment] 2023-08-11 10:09
Thanks for the great work on formkit ! We're using it with a confidence and lot of pleasure!

Just a head's up: I think this issue is a duplicate of issue https://github.com/formkit/formkit/issues/736

We have this problem as well. it's spamming our bug-monitoring tool, so i hope you may find some time to fix it !

Thanks in advance !

**Comment by justin-schroeder** [comment] 2023-08-11 13:46
Thanks for the great report @vmitchell85 — this is now fixed on the `@next` tag of `@formkit/pro` which should make its way to `@latest` today or early next week ❤️

**Closed** 2023-08-11 19:22 UTC
Labels: 🐛 bug, 🚀 release-ready, 🟡 priority-2, Pro
