### ISSUE TITLE
Possible memory problem during route switches

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#475] opened 2022-11-16 20:21 UTC
### Reproduction

https://github.com/dominikklein/formkit-possible-memory-problem

### Describe the bug

I found maybe a possible memory leak.
When I switch between two routes the memory is always increasing. So on one route, I have a form with some more fields (so that the memory increase is more visible) and the other route has no fields. Then I'm switching between the routes and see that the memory is always increasing and it will not be reduced when I go back to the route without the form.

Added a test repository with the "Home"-Route which has no FormKit-Form and the "About"-Route which has a bigger form.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by devoidofgenius** [comment] 2022-11-18 16:41
Thanks for providing a reproduction of the issue. We'll look into this further.

**Comment by justin-schroeder** [comment] 2022-11-22 17:54
Thanks for the reproduction. I've cloned it and played around with it some. It seems that the DOM nodes are not being GC'd consistently on unmount. Not sure yet if this is directly related to FormKit or something else, but will continue to look into it.

**Comment by KoenCa** [comment] 2023-01-30 08:19
Hey, we noticed this issue too when deploying several websites to production.

For example: we deployed a Nuxt 3 SSR website to a development environment that has a form on the home page. We have a monitoring tool that calls this home page to check for uptime. These calls alone cause a memory leak caused by formkit. I tested it locally with a node debugger. Refreshing the homepage with a Formkit form: memory keeps going up. Commenting out the Formkit form and doing the same: memory stats low.

This is pretty urgent, because this makes it impossible to deploy a website to production. For the development environment we didn't give it any limits and it used up to 7gb before being killed by the OOM killer...

**Comment by Timusan** [comment] 2023-01-30 08:23
Yes, same issue here. Impossible to use at this moment.

**Comment by KoenCa** [comment] 2023-01-30 12:42
I made a very basic reproduction in this repository: https://github.com/KoenCa/nuxt-formkit-memory-repro . Please see the README for instructions.

**Comment by KoenCa** [comment] 2023-01-30 14:41
I found a workaround for Nuxt 3: when we wrap FormKit forms or inputs with the `ClientOnly` component then there is no memory leak on the server.

**Comment by KoenCa** [comment] 2023-04-25 09:54
I just updated to latest formkit release via the `next` tag in my reproduction repository: https://github.com/KoenCa/nuxt-formkit-memory-repro . There is still a memory leak please see the following video:


https://user-images.githubusercontent.com/17332418/234241144-9027e42d-8caa-43c2-9f94-86ee2f7a4dec.mp4

**Comment by justin-schroeder** [comment] 2023-04-25 15:17
> I just updated to latest formkit release via the `next` tag in my reproduction repository: https://github.com/KoenCa/nuxt-formkit-memory-repro . **There is still a memory leak**, please see the following video:

Hmm, you're right. We fixed a server side memory issue and have a backing test for it using `createSSRApp`. Your nuxt app is exhibiting different behavior — I'm not sure what the precise difference is here, but some interaction of FormKit with Nuxt must be causing issues. Looking into it...

**Comment by justin-schroeder** [comment] 2023-04-26 18:32
@KoenCa I've updated `@formkit/nuxt` on the `@next` tag with an explicit memory clearing event after render along with a few other cleanups. This has dramatically improved GC in your test case — I manually call GC in this video so we dont have to wait for it to slowly spin down, but you get the idea.

I've also added a backing test for the nuxt server whose parameters are after 20 refreshes with GC memory cannot increase by 2mb.


https://user-images.githubusercontent.com/1950463/234670116-d68e1880-3823-4f99-99ff-a74035bf80ea.mov

**Comment by KoenCa** [comment] 2023-04-28 13:21
@justin-schroeder I've tested it again and indeed it looks like it is fixed now. Thanks!

**Comment by agenordebriat** [comment] 2023-05-03 15:07
@justin-schroeder Using `@next` fixed my GC/memory leaks issues on Nuxt, but it introduced something else.

I'm on my login route, that contains a FormKit form + login/password inputs, and I log in w/ a submit function that navigates me to another route on `POST` success.

Now, if I logout (clear cookies => don't have the rights to be there => get redirected back to the first route), I get :
`Uncaught (in promise) TypeError: compiledFns.get(...) is not a function`, and I'm stuck there since the route isn't being loaded.
If I do a hard refresh on the new route, I can go back to the login route properly.

I tried to remove the FormKit form node w/ everything inside, and it's fine. Also, if I wrap the FormKit form in a `<ClientOnly>` component, it's working, even though I'm not using SSR on this route. I also tried with `ssr: false`, and the `<ClientOnly>` component still fixes it.

On `0.16.5` everything's fine.

**Comment by justin-schroeder** [comment] 2023-05-03 15:12
Are you getting that error on the server side or client side? Any way you can create a reproduction?

**Comment by agenordebriat** [comment] 2023-05-03 15:15
Client side. Nothing pops up on the server side, as it should since SSR should be disabled.
Might be hard to provide a repro since it's on a work project. I'll try to do a quick CodeSandbox, see if it pops w/ the same kind of setup.

**Comment by justin-schroeder** [comment] 2023-05-03 15:16
The primary change between the two versions is we fully destroy the node once it is unmounted. Not sure why that would cause issues unless it is trying to reuse a component that has been unmounted? Perhaps something to do with keep-alive?

**Comment by agenordebriat** [comment] 2023-05-03 19:09
Narrowed it down to something weird : we already have a FormKit form element existing on the page, wrapped in a `<ClientOnly>` component somewhere else on the page. If none of the FormKit forms, or both of them, are in `<ClientOnly>` it's fine, but if only one of them is, it's not.
The other one currently needs it to fix an hydration issue, but I'm looking at fixing this so there's nothing to worry about.

Cannot wrap my head around why it behaves like this though.

**Comment by justin-schroeder** [comment] 2023-05-03 19:10
very very weird. Any chance they have a manually assigned `id`? And if so, any chance that `id` is the same on both of them?

**Comment by agenordebriat** [comment] 2023-05-03 19:17
They had no specific `id`, but I just tried assigning each one a unique `id` and it didn't change anything.

**Comment by justin-schroeder** [comment] 2023-05-03 20:20
Is this what you mean? 
![image](https://user-images.githubusercontent.com/1950463/236040189-189bbaf2-8f36-48d1-93ab-dfee7905b9ce.png)


Currently pro needs beta.16 to work properly — the refactors in @next require some additional tweaking to work (which is one reason why @next is still @next and not stable at @latest) We do have a `@formkit/pro@dev` tag that is tracking beta.17 but its pretty unstable still.

**Comment by agenordebriat** [comment] 2023-05-03 20:26
CodeSandbox appears to be unstable, I couldn't get it to work after seeing your message, but it now works again. You should see a single input in a form w/ some text.

**Comment by justin-schroeder** [comment] 2023-05-03 20:34
Yeah, we’re working as fast and hard as we can on that. Hate to give any explicit ETA because it always leads to sadness buuuut in terms of scope — I'd say its bigger than a breadbox, but smaller than an elephant.

**Comment by justin-schroeder** [comment] 2023-05-03 20:36
Also FWIW — the biggest thing about the using `@formkit/vue@next` with pro (@dev or not) is the repeater will not work correctly.

**Comment by agenordebriat** [comment] 2023-05-03 20:38
> Also FWIW — the biggest thing about the using `@formkit/vue@next` with pro (`@dev` or not) is the repeater will not work correctly.

This might explain some of the issues I encountered on another project then... 🥸

**Closed** 2023-05-12 19:24 UTC
Labels: 🐛 bug, 🚀 release-ready, 🥉 bronze-sponsor
